apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: banking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: banking
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: "banking-app"
        metrics_path: /metrics
        static_configs:
          - targets:
              - banking-app:8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus

  template:
    metadata:
      labels:
        app: prometheus

    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.4.0

          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus

          ports:
            - containerPort: 9090
              name: http

          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: prometheus-storage
              mountPath: /prometheus

          resources:
            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: 1
              memory: 1Gi

      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: banking
spec:
  selector:
    app: prometheus

  ports:
    - name: http
      port: 9090
      targetPort: http
